### ISSUE TITLE
vulnerability | API Visible 

### ISSUE THREAD

**Issue by abhaythakur71181** [BugReportOnWeb/stellar-visions#1]
![image](https://github.com/BugReportOnWeb/stellar-visions/assets/48170773/fdbbca67-7a85-402f-8379-2d030a9b45b4)

![](https://media1.tenor.com/m/S9WbzcQi5HAAAAAC/gecko-mad-lizard-mad.gif)

**Comment by BugReportOnWeb** [comment]
Can't do much about it 😔
